### ISSUE TITLE
"Read Item name From XML" gives error

### ISSUE THREAD

**Issue by Caduceus** [ottools/ItemEditor#10]
Perhaps I am not setting this up correctly. If so, can you inform me what is to be done so the program reads correctly? 

`>> System.Xml.XmlException: An error occurred while parsing EntityName. Line 38942, position 45.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.HandleEntityReference(Boolean isInAttributeValue, EntityExpandType expandType, Int32& charRefEndPos)
   at System.Xml.XmlTextReaderImpl.ParseAttributeValueSlow(Int32 curPos, Char quoteChar, NodeData attr)
   at System.Xml.XmlTextReaderImpl.ParseAttributes()
   at System.Xml.XmlTextReaderImpl.ParseElement()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at OTLib.Server.Items.ItemsXmlReader.Read(String directory, ServerItemList items)
`

**Comment by Mignari** [comment]
Do you use custom items.xml?
Maybe your items.xml file is malformed
The error message does not give much useful information

**Comment by Caduceus** [comment]
I had an item with "&" in the name on Line 38942, that was causing the issue.
